services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=challenge_fullstack'
      - 'MYSQL_PASSWORD=102030'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
